### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by Catalinex** [code4romania/code4.ro#112]
1. butoane floating de share page cu conter (FB, Lk, TW, Send mail) pe toate paginile site-ului inclusiv tfsg
2. buton de like page pe paginile din blog Fb, LK, Tw

**Comment by andreiio** [comment]
Sharing buttons are a bad idea for performance and privacy, fără să aducă un beneficiu suficient. Le-am evitat de la început.

Some references:

- https://insidegovuk.blog.gov.uk/2014/02/20/gov-uk-social-sharing-buttons-the-first-10-weeks/
- https://www.wearetheweather.co.uk/blog/social-buttons-poor-ux
- https://www.scottcole.net/5-genuine-reasons-stop-using-social-share-buttons/
- https://boagworld.com/design/social-media-buttons/
- https://solomon.io/why-im-done-with-social-media-buttons/
- https://bloomerang.co/blog/5-reasons-why-social-media-buttons-hurt-nonprofit-websites/
- https://thenextweb.com/insider/2015/12/23/the-hidden-cost-of-social-share-buttons/
