### ISSUE TITLE
Add pipeline build previews

### ISSUE THREAD

**Issue by andreiio** [code4romania/code4.ro#3]
**Is your feature request related to a problem? Please describe.**
There's currently no easy way to preview the outcome of changes in a branch / pull request without building it locally.

**Describe the solution you'd like**
An updated pipeline that would allow us to preview builds coming from (ordered by priority):

1. branches in this repository;
2. pull requests from this repository;
3. pull requests from forked repositories.

**Describe alternatives you've considered**
Netlify does [something similar](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/), but integrating this would require maintaining two different build definitions.

**Additional context**
Travis CI has some [security restrictions on pull requests](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) that would make this not work on pull requests coming from forked repositories.

**Comment by Utwo** [comment]
I can integrate a netlify or zeit now solution for this one.

**Comment by andreiio** [comment]
Hey, thanks for offering! We're currently planning to move to a different solution soon, which would render this feature useless.

**Comment by Utwo** [comment]
Ok, if you want I can help with that too.
