### ISSUE TITLE
Create CMS for website

### ISSUE THREAD

**Issue by overeha** [code4romania/code4.ro#93]
We will need a CMS - it  is unrealistic to be able to update the website in GitHub directly. As we will have more people coming on the team, who have to have access to this and none of them are tech savvy to this level, this needs to exist. 

Editable areas:
- homepage
- standalone pages
- blog posts
etc.

**Comment by Owlree** [comment]
I did some test drives with [Directus](https://directus.io/) for [Vot Diaspora](https://github.com/code4romania/vot-diaspora) and it seems to fit our needs. Very customizable, easy to build content translation schema, good WYSIWYG editor.

That only thing that lacks is a preview (it does have formatting preview, but you can't preview how the content will look on the actual website). I think we can build one, but I would prioritize that necessarily.

What do you say?

**Comment by andreiio** [comment]
Being worked on in [code4romania/cms](https://github.com/code4romania/cms).
